name: Clang

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prerequisites
      run: |
        sudo apt update
        sudo apt install clang-15 cmake ninja libicu-dev valgrind

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -G -DCMAKE_C_COMPILER=/usr/bin/clang-15 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15 ..
        ninja

    - name: Test
      run: |
        cd out
        valgrind --leak-check=yes ./pystykorva_tests

